import { cp, mkdir, readFile, rm, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { findPageConfigs } from "./pages.mjs";
import { render } from "./lib/html.mjs";
import { applyPageTransforms } from "./lib/page-transforms.mjs";
import { primaryHrefForOutput, rootForOutput } from "./lib/paths.mjs";
import {
  renderNavigation,
  renderOverlayNavigation,
  renderPageAnchors,
  renderPageHero,
  renderPageRelated
} from "./lib/renderers.mjs";

const projectRoot = process.cwd();
const sourceRoot = join(projectRoot, "src");
const read = (path) => readFile(path, "utf8");
const readOptional = async (path) => {
  try {
    return await read(path);
  } catch (error) {
    if (error.code === "ENOENT") return "";
    throw error;
  }
};

const site = JSON.parse(await read(join(sourceRoot, "data", "site.json")));
const pages = await findPageConfigs(projectRoot);
const templates = Object.fromEntries(await Promise.all([
  "document-start",
  "header",
  "overlay-menu",
  "page-kv",
  "page-anchors",
  "page-related",
  "contact",
  "footer-wave",
  "floating-cta",
  "footer",
  "scripts"
].map(async (name) => [name, await read(join(sourceRoot, name === "document-start" ? "layouts" : "components", `${name}.html`))])));

for (const { directory: pageDirectory, config } of pages) {
  const root = rootForOutput(projectRoot, config.output);
  const overlayNavigation = renderOverlayNavigation(site.overlayNavigation, root);
  const [pageMainSource, pageAfterContact] = await Promise.all([
    read(join(pageDirectory, "main.html")),
    readOptional(join(pageDirectory, "after-contact.html"))
  ]);
  const pageMain = applyPageTransforms(pageMainSource, config.output);
  const context = {
    root,
    title: config.title,
    description: config.description,
    canonical: config.canonical,
    preload: config.preload ? render(config.preload, { root }) : "",
    contactTelHref: site.contact.telHref,
    contactTelDisplay: site.contact.telDisplay,
    contactHours: site.contact.hours,
    primaryNavigation: renderNavigation(site.primaryNavigation, root, "primary", primaryHrefForOutput(config.output)),
    overlayNavigation: overlayNavigation.cards,
    overlayNavigationDetails: overlayNavigation.details,
    footerNavigation: renderNavigation(site.footerNavigation, root, "footer"),
    pageHero: config.hero ? renderPageHero(templates["page-kv"], config.hero, root) : "",
    pageAnchors: config.anchorNavigation ? renderPageAnchors(templates["page-anchors"], config.anchorNavigation) : "",
    pageRelated: config.related ? renderPageRelated(templates["page-related"], config.related, root) : ""
  };

  const html = [
    "<!-- Generated by npm run build. Edit src/ files, not this file. -->",
    render(templates["document-start"], context),
    render(templates.header, context),
    render(templates["overlay-menu"], context),
    render(pageMain, context),
    render(templates.contact, context),
    render(pageAfterContact, context),
    "</main>",
    render(templates["footer-wave"], context),
    render(templates["floating-cta"], context),
    render(templates.footer, context),
    render(templates.scripts, context)
  ].join("\n");

  const output = join(projectRoot, config.output);
  await mkdir(dirname(output), { recursive: true });
  await writeFile(output, html, "utf8");
}

await rm(join(projectRoot, "css"), { recursive: true, force: true });
await rm(join(projectRoot, "js"), { recursive: true, force: true });
await rm(join(projectRoot, "images"), { recursive: true, force: true });
await cp(join(sourceRoot, "assets", "css"), join(projectRoot, "css"), { recursive: true });
await cp(join(sourceRoot, "assets", "js"), join(projectRoot, "js"), { recursive: true });
await cp(join(sourceRoot, "assets", "images"), join(projectRoot, "images"), { recursive: true });
await rm(join(projectRoot, "images", "selected", "originals"), { recursive: true, force: true });
await rm(join(projectRoot, "images", "selected", "README.md"), { force: true });
await rm(join(projectRoot, "images", "selected", "selection-map.csv"), { force: true });

console.log(`Built ${pages.length} GitHub Pages preview pages from src/.`);
