import { cp, mkdir, readFile, readdir, rm, writeFile } from "node:fs/promises";
import { dirname, join, relative } from "node:path";

const projectRoot = process.cwd();
const sourceRoot = join(projectRoot, "src");
const read = (path) => readFile(path, "utf8");

function siteHref(root, href) {
  return href.startsWith("#") || /^(https?:|mailto:|tel:)/.test(href) ? href : `${root}${href}`;
}

function renderNavigation(items, root, type, activePrimaryHref = null) {
  if (type === "primary") {
    return `<ul>\n${items.map((item) => {
      const isCurrent = item.href === activePrimaryHref;
      const currentAttributes = isCurrent ? ' class="is-current" aria-current="page"' : '';
      return `        <li><a href="${siteHref(root, item.href)}"${currentAttributes}>${item.label}</a></li>`;
    }).join("\n")}\n      </ul>`;
  }

  if (type === "overlay") {
    return items.map((item) => `        <li class="overlay-nav__item">
          <span class="overlay-nav__num" aria-hidden="true">${item.number}</span>
          <a href="${siteHref(root, item.href)}" class="overlay-nav__link">
            <span class="overlay-nav__en">${item.en}</span>
            <span class="overlay-nav__jp">${item.jp}</span>
          </a>
          <ul class="overlay-nav__sub">
${item.children.map((child) => `            <li><a href="${siteHref(root, child.href)}">${child.label}</a></li>`).join("\n")}
          </ul>
        </li>`).join("\n");
  }

  return items.map((item) => `      <div class="site-footer__col">
        <p class="site-footer__col-title"><a href="${siteHref(root, item.href)}">${item.label}</a></p>
        <ul>
${item.children.map((child) => `          <li><a href="${siteHref(root, child.href)}">${child.label}</a></li>`).join("\n")}
        </ul>
      </div>`).join("\n");
}

function render(template, context) {
  return template.replace(/{{([a-zA-Z]+)}}/g, (token, key) => context[key] ?? token);
}

const site = JSON.parse(await read(join(sourceRoot, "data", "site.json")));
async function findPageDirectories(directory) {
  const entries = await readdir(directory, { withFileTypes: true });
  const pages = [];

  for (const entry of entries) {
    if (!entry.isDirectory()) continue;
    const childDirectory = join(directory, entry.name);
    const childEntries = await readdir(childDirectory);
    if (childEntries.includes("page.json")) pages.push(childDirectory);
    pages.push(...await findPageDirectories(childDirectory));
  }

  return pages;
}

function rootForOutput(output) {
  const outputDirectory = dirname(join(projectRoot, output));
  const pathToRoot = relative(outputDirectory, projectRoot).replaceAll("\\", "/");
  return pathToRoot ? `${pathToRoot}/` : "./";
}

function primaryHrefForOutput(output) {
  if (output === "index.html") return null;
  return `${output.split("/")[0]}/`;
}

const pageDirectories = (await findPageDirectories(join(sourceRoot, "pages"))).sort();

const templates = await Promise.all([
  read(join(sourceRoot, "layouts", "document-start.html")),
  read(join(sourceRoot, "components", "header.html")),
  read(join(sourceRoot, "components", "overlay-menu.html")),
  read(join(sourceRoot, "components", "contact.html")),
  read(join(sourceRoot, "components", "footer-wave.html")),
  read(join(sourceRoot, "components", "floating-cta.html")),
  read(join(sourceRoot, "components", "footer.html")),
  read(join(sourceRoot, "components", "scripts.html"))
]);

for (const pageDir of pageDirectories) {
  const config = JSON.parse(await read(join(pageDir, "page.json")));
  const root = rootForOutput(config.output);
  const [pageMain, pageAfterContact] = await Promise.all([
    read(join(pageDir, "main.html")),
    read(join(pageDir, "after-contact.html"))
  ]);
  const [layout, header, overlay, contact, footerWave, floatingCta, footer, scripts] = templates;
  const context = {
    root,
    title: config.title,
    description: config.description,
    canonical: config.canonical,
    preload: config.preload ? render(config.preload, { root }) : "",
    primaryNavigation: renderNavigation(site.primaryNavigation, root, "primary", primaryHrefForOutput(config.output)),
    overlayNavigation: renderNavigation(site.overlayNavigation, root, "overlay"),
    footerNavigation: renderNavigation(site.footerNavigation, root, "footer")
  };

  const html = [
    "<!-- Generated by npm run build. Edit src/ files, not this file. -->",
    render(layout, context),
    render(header, context),
    render(overlay, context),
    pageMain,
    render(contact, context),
    pageAfterContact,
    "</main>",
    render(footerWave, context),
    render(floatingCta, context),
    render(footer, context),
    render(scripts, context)
  ].join("\n");

  const output = join(projectRoot, config.output);
  await mkdir(dirname(output), { recursive: true });
  await writeFile(output, html, "utf8");
}

await rm(join(projectRoot, "css"), { recursive: true, force: true });
await rm(join(projectRoot, "js"), { recursive: true, force: true });
await rm(join(projectRoot, "images"), { recursive: true, force: true });
await cp(join(sourceRoot, "assets", "css"), join(projectRoot, "css"), { recursive: true });
await cp(join(sourceRoot, "assets", "js"), join(projectRoot, "js"), { recursive: true });
await cp(join(sourceRoot, "assets", "images"), join(projectRoot, "images"), { recursive: true });

console.log(`Built ${pageDirectories.length} GitHub Pages preview pages from src/.`);
