import { access, readFile } from "node:fs/promises";
import { join, dirname } from "node:path";

const root = process.cwd();
const outputs = ["index.html", "about/index.html", "access/index.html", "services/index.html", "pricing/index.html", "target/index.html"];
const generatedMarker = "<!-- Generated by npm run build. Edit src/ files, not this file. -->";
const attributePattern = /(?:src|href)="([^"#?]+)"/g;
const assetPattern = /\.(?:css|js|png|jpe?g|webp|svg)$/i;
const externalPattern = /^(?:https?:|mailto:|tel:|data:|javascript:)/i;
const errors = [];

for (const output of outputs) {
  const file = join(root, output);
  const html = await readFile(file, "utf8");

  if (!html.startsWith(generatedMarker)) errors.push(`${output}: generated marker is missing.`);
  if (html.includes("{{")) errors.push(`${output}: unresolved template token found.`);

  for (const match of html.matchAll(attributePattern)) {
    const reference = match[1];
    if (externalPattern.test(reference) || !assetPattern.test(reference)) continue;
    try {
      await access(join(dirname(file), reference));
    } catch {
      errors.push(`${output}: missing local asset ${reference}`);
    }
  }
}

const stylesheet = join(root, "css", "style.css");
const stylesheetSource = await readFile(stylesheet, "utf8");
for (const match of stylesheetSource.matchAll(/@import url\("([^"\)]+)"\);/g)) {
  try {
    await access(join(dirname(stylesheet), match[1]));
  } catch {
    errors.push(`css/style.css: missing imported stylesheet ${match[1]}`);
  }
}

if (errors.length) {
  console.error(errors.join("\n"));
  process.exit(1);
}

console.log(`Verified ${outputs.length} generated pages: templates and local assets are valid.`);
